const fs = require('fs');
const path = require('path');

let logoCache;
function logoBase64() {
  if (logoCache !== undefined) return logoCache;
  try {
    const buf = fs.readFileSync(path.join(__dirname, '..', 'logo.png'));
    logoCache = `data:image/png;base64,${buf.toString('base64')}`;
  } catch {
    logoCache = '';
  }
  return logoCache;
}

const STYLES = `
@page { margin: 40px; }
body { font-family: Arial, sans-serif; font-size: 11px; line-height: 1.5; color: #333; }
.header { display: flex; align-items: center; margin-bottom: 10px; padding-bottom: 10px; }
.logo { width: 80px; height: 80px; margin-right: 20px; }
h1 { font-family: 'Bebas Neue', Arial, sans-serif; font-size: 28px; color: #000; margin: 0; letter-spacing: 1px; }
h2 { font-family: 'Bebas Neue', Arial, sans-serif; font-size: 20px; color: #000; margin: 0 0 5px 0; letter-spacing: 0.5px; }
.red-line { height: 3px; background-color: #E31837; margin: 15px 0 20px 0; }
.section { margin-bottom: 20px; }
.section-header { font-family: 'Bebas Neue', Arial, sans-serif; font-size: 16px; color: #000; margin-bottom: 10px; letter-spacing: 0.5px; }
.info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-bottom: 15px; }
.info-item { font-size: 10px; }
.label { font-weight: bold; color: #000; }
.fin-table { width: 100%; font-size: 10px; border-collapse: collapse; }
.fin-table td { padding: 6px 8px; border-bottom: 1px solid #ddd; }
.fin-table td:first-child { font-weight: bold; width: 60%; }
.footer { margin-top: 40px; font-size: 9px; color: #666; }
`;

function escape(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

function render({ requestId, occurredAt, data, member }) {
  const m = data.member || {};
  const r = data.result || {};
  const f = data.financials || {};
  const fullName = `${member.firstName} ${member.lastName}`.trim() || '(name not on file)';

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
  <style>${STYLES}</style>
</head>
<body>
  <div class="header">
    <img src="${logoBase64()}" class="logo" alt="WCS Logo">
    <div>
      <h1>WEST COAST STRENGTH</h1>
      <h2>CANCELLATION RECORD</h2>
    </div>
  </div>
  <div class="red-line"></div>

  <div class="section">
    <div class="section-header">MEMBER</div>
    <div class="info-grid">
      <div class="info-item"><span class="label">Name:</span> ${escape(fullName)}</div>
      <div class="info-item"><span class="label">Email:</span> ${escape(m.email)}</div>
      <div class="info-item"><span class="label">Member ID:</span> ${escape(m.memberId)}</div>
      <div class="info-item"><span class="label">Agreement ID:</span> ${escape(m.agreementId)}</div>
      <div class="info-item"><span class="label">Barcode:</span> ${escape(m.barcode)}</div>
      <div class="info-item"><span class="label">Club Code:</span> ${escape(data.clubCode)}</div>
    </div>
  </div>

  <div class="section">
    <div class="section-header">CANCELLATION DETAILS</div>
    <div class="info-grid">
      <div class="info-item"><span class="label">Status:</span> ${escape(r.status)}</div>
      <div class="info-item"><span class="label">Effective Date:</span> ${escape(r.effectiveDate)}</div>
      <div class="info-item"><span class="label">Cancel Code:</span> ${escape(r.cancelCode)}</div>
      <div class="info-item"><span class="label">Cancel Reason:</span> ${escape(r.cancelReason)}</div>
      <div class="info-item"><span class="label">Buyer's Remorse:</span> ${r.buyerRemorseApplied ? 'Yes' : 'No'}</div>
    </div>
  </div>

  <div class="section">
    <div class="section-header">FINANCIALS</div>
    <table class="fin-table">
      <tr><td>Past Due Balance</td><td>$${escape(f.pastDueBalance)}</td></tr>
      <tr><td>Past Due Collected</td><td>$${escape(f.pastDueCollected)}</td></tr>
      <tr><td>Next Due Amount</td><td>$${escape(f.nextDueAmount)}</td></tr>
      <tr><td>Next Due Collected</td><td>$${escape(f.nextDueCollected)}</td></tr>
      <tr><td>Buyout Amount</td><td>$${escape(f.buyoutAmount)}</td></tr>
      <tr><td>Buyout Collected</td><td>$${escape(f.buyoutCollected)}</td></tr>
    </table>
  </div>

  <div class="footer">
    Generated by Click2Save → WCS &nbsp;·&nbsp; Request ID: ${escape(requestId)} &nbsp;·&nbsp; Occurred At: ${escape(occurredAt)}
  </div>
</body>
</html>`;
}

module.exports = { render };
